version: "3.2"

networks:
  stack:
    driver: bridge

volumes:
  esdata:
    driver: local

services:

  devportal:
    image: ${REG}webmethods-devportal-standalone:${TAG_PORTAL}
    ports:
      - "18101:18101"
      - "18102:18102"
    environment: 
      JAVA_MIN_MEM: 512m
      JAVA_MAX_MEM: 512m
      IDS_HEAP_SIZE: 512m
      JAVA_OPTS: ""
      PORTAL_SERVER_CONFIG_LICENSE: /opt/softwareag/licenseKey.xml
    volumes:
      - ../licensing/devportal-licenseKey.xml:/opt/softwareag/licenseKey.xml:ro
      - esdata:/data
    hostname: devportal
    networks:
      - stack