version: "3.2"

networks:
  stack:
    driver: bridge

services:

  devportal:
    image: ${REG}webmethods-devportal:${TAG_PORTAL}
    ports:
      - "18101:18101"
      - "18102:18102"
    environment: 
      JAVA_MIN_MEM: 512m
      JAVA_MAX_MEM: 512m
      JAVA_OPTS: ""
      PORTAL_SERVER_CONFIG_TENANT: default
      PORTAL_SERVER_CONFIG_LICENSE: /opt/softwareag/licenseKey.xml
    volumes:
      - ./licensing/devportal-licenseKey.xml:/opt/softwareag/licenseKey.xml:ro
    hostname: devportal
    networks:
      - stack

  devportal_configurator:
    image: ${REG}webmethods-devportal-configurator:${TAG_PORTAL_CONFIGURATOR}
    volumes:
      - ./local/sagdevops-ansible-roles:/ansible/roles/sagdevops-ansible-roles-dev-0.2.4:ro
    environment:
      env_devportal_protocol: http
      env_devportal_host: devportal
      env_devportal_port: "18101"
      env_devportal_rest_user: Administrator
      env_devportal_rest_password: "${SAG_PASSWORD}"
      env_devportal_rest_password_old: "manage"
      env_devportal_configure_default_ignore_errors: "true"
      env_devportal_configure_usermgt: "true"
      env_devportal_configure_usermgt_ignore_errors: "false"
      env_devportal_users_sample1_password: password1!
      env_devportal_users_sample2_password: password2!
      env_devportal_users_sample3_password: password3!
    networks:
      - stack
