version: "3.2"

networks:
  stack:

services:

  caching_client:
    image: ${REG}webmethods-terracotta/sample-caching-client:${TAG_TERRACOTTA}
    build:
      context: ../sample-ehcache-client
      dockerfile: Dockerfile
      args:
        BUILDER_IMAGE: ${REG}webmethods-terracotta:${TAG_TERRACOTTA}
    volumes:
      - ${PWD}/licensing/terracotta-license.key:/var/run/terracotta-license.key:ro
    environment: 
      - LICENSE_FILE=/var/run/terracotta-license.key
      - TERRACOTTA_SERVER_URL=terracotta1:9510,terracotta2:9510
      - JAVA_OPTS=-Dcom.tc.tc.config.total.timeout=60000
    networks:
      - stack

  terracotta1:
    image: ${REG}webmethods-terracotta:${TAG_TERRACOTTA}
    hostname: terracotta1
    volumes:
      - ${PWD}/licensing/terracotta-license.key:/var/run/terracotta-license.key:ro
    environment: 
      - LICENSE_FILE=/var/run/terracotta-license.key
      - TSA_PORT="9510"
      - JMX_PORT="9520"
      - GROUP_PORT="9530"
      - MGT_PORT="9540"
      - HEAP_SIZE_MB_MIN="512m"
      - HEAP_SIZE_MB_MAX="1024m"
      - DATA_STORAGE_SIZE="20g"
      - DATA_OFFHEAP_SIZE="1g"
      - RESTARTABLE_ENABLED="false"
      - TC_SERVER_HOST1="terracotta1"
      - TC_SERVER_HOST2="terracotta2"
    networks:
      - stack

  terracotta2:
    image: ${REG}webmethods-terracotta:${TAG_TERRACOTTA}
    hostname: terracotta2
    volumes:
      - ${PWD}/licensing/terracotta-license.key:/var/run/terracotta-license.key:ro
    environment: 
      - LICENSE_FILE=/var/run/terracotta-license.key
      - TSA_PORT="9510"
      - JMX_PORT="9520"
      - GROUP_PORT="9530"
      - MGT_PORT="9540"
      - HEAP_SIZE_MB_MIN="512m"
      - HEAP_SIZE_MB_MAX="1024m"
      - DATA_STORAGE_SIZE="20g"
      - DATA_OFFHEAP_SIZE="1g"
      - RESTARTABLE_ENABLED="false"
      - TC_SERVER_HOST1="terracotta1"
      - TC_SERVER_HOST2="terracotta2"
    networks:
      - stack

  tmc:
    image: ${REG}webmethods-terracotta-tmc:${TAG_TERRACOTTA}
    ports:
      - 9889:9889
      - 9443:9443
    hostname: tmc
    volumes:
      - ${PWD}/licensing/terracotta-license.key:/var/run/terracotta-license.key:ro
    environment: 
      - LICENSE_FILE=/var/run/terracotta-license.key
    networks:
      - stack