# Configurator for apigateway
---
apiVersion: batch/v1
kind: Job
metadata:
  name: webmethods-apigateway-configurator
  labels:
    app.kubernetes.io/name: webmethods-apigateway-configurator
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 1800
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: webmethods-apigateway-configurator
          image: 815840818766.dkr.ecr.us-east-1.amazonaws.com/webmethods-apigateway-configurator:configurator-10.7.7-3
          args: ["apply_configs.yaml"]
          env:
            - name: env_apigateway_configure_default_ignore_errors
              value: "false"
            - name: env_apigateway_configure_lb
              value: "true"
            - name: env_apigateway_configure_extended_settings
              value: "true"
            - name: env_apigateway_configure_portalgateway
              value: "true"
            - name: env_apigateway_configure_portalgateway_ignore_errors
              value: "true"
            - name: env_apigateway_host
              value: "webmethods-apigateway-standalone"
            - name: env_apigateway_port
              value: "5555"
            - name: env_apigateway_rest_user
              value: "Administrator"
            - name: env_apigateway_rest_password_old
              value: "manage"
            - name: env_apigateway_rest_password
              value: "newpassword"
            - name: env_apigateway_portalgateway_gateway_url
              value: "http://webmethods-apigateway-standalone:5555"
            - name: env_apigateway_portalgateway_gateway_username
              value: "Administrator"
            - name: env_apigateway_portalgateway_gateway_password
              value: "newpassword"
            - name: env_apigateway_portalgateway_portaltype
              value: apiportal
            - name: env_apigateway_portalgateway_apiportal_url
              value: "http://webmethods-apiportal-standalone:18101"
            - name: env_apigateway_portalgateway_apiportal_tenant
              value: "default"
            - name: env_apigateway_portalgateway_apiportal_username
              value: "system"
            - name: env_apigateway_portalgateway_apiportal_password
              value: "newpassword"
            - name: env_apigateway_lb_http_url
              value: http://webmethods-apigateway.demo1.apimgt.cloud
            - name: env_apigateway_lb_https_url
              value: https://webmethods-apigateway.demo1.apimgt.cloud
            - name: env_apigateway_lb_websocket_url
              value: "ws://webmethods-apigateway.demo1.apimgt.cloud"
            - name: env_apigateway_lb_http_url_alt1
              value: http://webmethods-apigateway-standalone:5555
            - name: env_apigateway_lb_https_url_alt1
              value: https://webmethods-apigateway-standalone:5443
            - name: env_apigateway_lb_websocket_url_alt1
              value: "ws://webmethods-apigateway-standalone:5555"
            - name: env_apigateway_lb_webapp_url
              value: http://webmethods-apigateway.demo1.apimgt.cloud