version: "3.2"

networks:
  stack:

services:

  apigateway:
    image: ${REG}webmethods-apigateway-standalone:${TAG_APIGATEWAY}
    ports:
      - "5555:5555"
      - "9072:9072"
    environment: 
      APIGW_ELASTICSEARCH_TENANTID: apigateway
      JAVA_MIN_MEM: 512m
      JAVA_MAX_MEM: 512m
      JAVA_OPTS: ""
      RUNTIME_WATT_PROPERTIES: "watt.net.timeout=400 watt.server.threadPool=800 watt.server.threadPoolMin=25 watt.net.maxClientKeepaliveConns=10 test.test=something=2"
    volumes:
      - ../licensing/apigateway-licenseKey.xml:/opt/softwareag/IntegrationServer/instances/default/config/licenseKey.xml:rw
    hostname: apigateway
    networks:
      - stack

  webmethods-sample-apis-uszip:
    image: ${REG}webmethods-sample-apis-uszip:${TAG_SAMPLE_APIS}
    expose:
      - "7071"
    ports:
      - "7071:7071"
    networks:
      - stack

  webmethods-sample-apis-bookstore:
    image: ${REG}webmethods-sample-apis-bookstore:${TAG_SAMPLE_APIS}
    expose:
      - "7071"
    ports:
      - "7072:7071"
    networks:
      - stack

  apigateway_configurator:
    image: ${REG}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    environment: 
      env_apigateway_host: apigateway
      env_apigateway_port: "5555"
      env_apigateway_rest_user: Administrator
      env_apigateway_rest_password_old: "manage"
      env_apigateway_rest_password: "${SAG_PASSWORD}"
      env_apigateway_configure_lb: "true"
      env_apigateway_lb_http_url: "http://localhost"
      env_apigateway_lb_https_url: ""
      env_apigateway_lb_websocket_url: ""
      env_apigateway_lb_webapp_url: "http://localhost"
    networks:
      - stack