---
deployment:
  replicas: 2

logs:
  access:
    enabled: true

providers:
  kubernetesCRD:
    allowCrossNamespace: true

additionalArguments:
  # Don't match backend certs
  - --serverstransport.insecureskipverify=true
  - --log.level=INFO
  # - --api.insecure=true

ingressRoute:
  dashboard:
    enabled: false

ingressClass:
  enabled: true
  isDefaultClass: true
  # name: my-custom-class

ports:
  web:
    enabled: true
    # redirectTo: websecure
  websecure:
    enabled: true
    tls:
      enabled: true

## annotation for AZURE
# service:
#   annotations:
#     service.beta.kubernetes.io/azure-load-balancer-internal: "true"
#     service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "snet-clusteringressservices"

## annotations for AWS NLB
# service:
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-internal: "true"
#     service.beta.kubernetes.io/aws-load-balancer-type: nlb
#     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
#     service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
#     service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

resources:
  requests:
    memory: "250Mi"
    cpu: "100m"
  limits:
    memory: "500Mi"
    cpu: "300m"
