---

image:
  registry: ghcr.io/softwareag-government-solutions
  repository: webmethods-devportal
  pullPolicy: IfNotPresent
  tag: 10.11-latest

imagePullSecrets:
  - name: saggov-ghcr

licenseSecret:
  name: softwareag-apimgt-licenses
  key: devportal-license
  path: license.xml

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

resources:
  requests:
    memory: 512Mi
    cpu: 500m
  limits:
    memory: 1280Mi
    cpu: 1

settings:
  tenant: default
  loadbalancerUrl: http://webmethods-devportal.cluster-demo.apimgt.saggov/portal
  javaMemMin: 512m
  javaMemMax: 1g
  javaOpts: ""
  clustering:
    enabled: true
  elastic:
    uris: http://elasticsearch-es-sag-apidatastore:9200
    username: elastic
    passwordSecret:
      name: elasticsearch-es-elastic-user
      key: elastic

waitforelastic:
  enabled: true
  uri: http://elasticsearch-es-sag-apidatastore:9200
  username: elastic
  passwordSecret:
    name: elasticsearch-es-elastic-user
    key: elastic

configurator:
  enabled: true
  settings:
    restUsername: Administrator
    restPasswordSecret:
      name: softwareag-apimgt-devportal-passwords
      key: Administrator
    restPasswordOldSecret:
      name: softwareag-apimgt-devportal-passwords
      key: AdministratorOld

# UI ingress
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: webmethods-devportal.cluster-demo.apimgt.saggov
      paths:
        - path: /
          pathType: Prefix