---

image:
  registry: ghcr.io/softwareag-government-solutions
  repository: webmethods-devportal
  pullPolicy: IfNotPresent
  tag: 10.11-latest

imagePullSecrets:
  - name: saggov-ghcr

licenseSecret:
  name: softwareag-apimgt-licenses
  key: devportal-license
  path: license.xml

replicaCount: 2

settings:
  tenant: default
  loadbalancerUrl: http://webmethods-devportal.cluster-demo.apimgt.saggov/portal
  javaMemMin: 1g
  javaMemMax: 1g
  javaOpts: ""
  clustering:
    enabled: true
  elastic:
    uris: http://elasticsearch-es-sag-apidatastore:9200
    username: elastic
    passwordSecret:
      name: elasticsearch-es-elastic-user
      key: elastic

configurator:
  enabled: true
  envConfigs:
    env_devportal_configure_default_ignore_errors: false
    env_devportal_protocol: http
    env_devportal_host: webmethods-devportal
    env_devportal_port: 18101
    env_devportal_no_check_certs: true
    env_devportal_rest_user: Administrator
    env_devportal_rest_password_old: manage
  envSecretConfigs:
    env_devportal_rest_password:
      secretKeyRef: softwareag-apimgt-app-passwords
      key: administrator

waitforelastic:
  enabled: true
  uri: http://elasticsearch-es-sag-apidatastore:9200
  username: elastic
  passwordSecret:
    name: elasticsearch-es-elastic-user
    key: elastic

# UI ingress
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: webmethods-devportal.cluster-demo.apimgt.saggov
      paths:
        - path: /
          pathType: Prefix
