version: "3.9"

networks:
  stack:

volumes:
  esdata:
    driver: local

services:

  devportal1:
    image: ${REG_DEVPORTAL}${REPO_DEVPORTAL}:${TAG_DEVPORTAL}
    ports:
      - 8083:8083
      - 8084:8084
    environment: 
      JAVA_MIN_MEM: 512m
      JAVA_MAX_MEM: 512m
      JAVA_OPTS: ""
      SPRING_ELASTICSEARCH_REST_URIS: "http://elasticsearch:9200"
      PORTAL_SERVER_CONFIG_LICENSE: "/opt/softwareag/licenseKey.xml"
      PORTAL_SERVER_CACHE_DISTRIBUTED_ENABLED: "true"
      PORTAL_SERVER_CACHE_DISTRIBUTED_CLUSTER_PEERS_0: "devportal1:47500..47509"
      PORTAL_SERVER_CACHE_DISTRIBUTED_CLUSTER_PEERS_1: "devportal2:47500..47509"
      # PORTAL_SERVER_CONFIG_TENANT: "${TENANTID}"
    volumes:
      -  ../licensing/devportal-licenseKey.xml:/opt/softwareag/licenseKey.xml:ro
    networks:
      - stack
    depends_on: 
      - elasticsearch

  devportal2:
    image: ${REG_DEVPORTAL}${REPO_DEVPORTAL}:${TAG_DEVPORTAL}
    ports:
      - 18083:8083
      - 18084:8084
    environment: 
      JAVA_MIN_MEM: 512m
      JAVA_MAX_MEM: 512m
      JAVA_OPTS: ""
      SPRING_ELASTICSEARCH_REST_URIS: "http://elasticsearch:9200"
      PORTAL_SERVER_CONFIG_LICENSE: "/opt/softwareag/licenseKey.xml"
      PORTAL_SERVER_CACHE_DISTRIBUTED_ENABLED: "true"
      PORTAL_SERVER_CACHE_DISTRIBUTED_CLUSTER_PEERS_0: "devportal1:47500..47509"
      PORTAL_SERVER_CACHE_DISTRIBUTED_CLUSTER_PEERS_1: "devportal2:47500..47509"
      # PORTAL_SERVER_CONFIG_TENANT: "${TENANTID}"
    volumes:
      - ../licensing/devportal-licenseKey.xml:/opt/softwareag/licenseKey.xml:rw
    networks:
      - stack
    depends_on: 
      - elasticsearch

  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: ${IMAGE_ELASTIC}:${TAG_ELASTIC}
    expose:
      - "9200"
      - "9300"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - http.port=9200
      - transport.port=9300
    volumes:
      - esdata:/data
    mem_limit: 2gb
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
      - stack