---
image:
  registry: ghcr.io/softwareag-government-solutions
  repository: webmethods-sample-apis-bookstore
  pullPolicy: IfNotPresent
  tag: dev-0.0.4

imagePullSecrets:
  - name: saggov-ghcr

fullnameOverride: sampleapis-bookstore-samplejavaapis

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1024Mi
    cpu: 1

service:
  port: 7071

# app specifics
appPort: 7071
appContextPath: /bookstore
appHealthCheckPath: /books/0
appHealthCheckHeaders: []
