---
image:
  registry: ghcr.io/softwareag-government-solutions
  repository: webmethods-sample-apis-uszip
  pullPolicy: IfNotPresent
  tag: dev-0.0.4

imagePullSecrets:
  - name: saggov-ghcr

replicaCount: 2

fullnameOverride: sampleapis-uszip-samplejavaapis

resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 500m

service:
  port: 7071

# app specifics
appPort: 7071
appContextPath: /uszip
appHealthCheckPath: /findZip/city/statecode
appHealthCheckHeaders: []
