---
image:
  registry: ghcr.io/softwareag-government-solutions
  repository: webmethods-sample-apis-uszip
  pullPolicy: IfNotPresent
  tag: dev-0.0.4

imagePullSecrets:
  - name: saggov-ghcr

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

fullnameOverride: sampleapis-uszip-samplejavaapis

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1024Mi
    cpu: 1

service:
  port: 7071

# app specifics
appPort: 7071
appContextPath: /uszip
appHealthCheckPath: /findZip/city/statecode
appHealthCheckHeaders: []
