---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.13.4
  count: 2
  elasticsearchRef:
    name: elasticsearch
  config:
    server.basePath: /apigatewayui/dashboardproxy
    server.rewriteBasePath: false
    kibana.index: gateway_apigateway_dashboard
  podTemplate:
    spec:
      initContainers:
        - name: wait-for-apigw
          image: curlimages/curl:7.81.0
          command:
            [
              "sh",
              "-c",
              "until curl -k -f -s -H 'Accept:application/json' --connect-timeout 2 --max-time 5 http://apigateway-gwruntime:5555/rest/apigateway/health; do echo waiting for apigateway to start...; sleep 10; done; echo apigateway started!",
            ]
      containers:
        - name: kibana
          env:
            - name: ELASTICSEARCH_USERNAME
              value: elastic
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-es-elastic-user
                  key: elastic
  http:
    tls:
      selfSignedCertificate:
        disabled: true
