version: "3.2"

networks:
  apigwnet:

x-aws-vpc: ${TARGET_VPC}
x-aws-loadbalancer: ${TARGET_LOADBALANCER}

services:

  reverseproxy_nginx:
    image: ${REG_ECS}webmethods-apigateway-reverseproxy:${TAG_APIGATEWAY:-dev-10.7-latest}
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - target: 80
        x-aws-protocol: http
    networks:
      - apigwnet

  apigateway:
    image: ${REG_ECS}webmethods-apigateway-standalone:${TAG_APIGATEWAY:-dev-10.7-latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${REG:-harbor.saggs.cloud/library/}webmethods-apigateway-standalone:${TAG_APIGATEWAY:-dev-10.7-latest}
    environment: 
      APIGW_ELASTICSEARCH_TENANTID: apigateway
      JAVA_MIN_MEM: 1g
      JAVA_MAX_MEM: 2g
      JAVA_OPTS: "-Dtest2=test2 -Dtest3=test3 -Dtest4=test4"
      RUNTIME_WATT_PROPERTIES: "watt.net.timeout=400 watt.server.threadPool=800 watt.server.threadPoolMin=25 watt.net.maxClientKeepaliveConns=10 test.test=something=2"
    hostname: apigateway
    networks:
      - apigwnet