version: "3.2"

networks:
  apigwnet:

x-aws-vpc: ${TARGET_VPC}
x-aws-loadbalancer: ${TARGET_LOADBALANCER}
x-aws-cluster: ${TARGET_ECS_CLUSTER}

services:

  apigateway_configurator:
    image: ${REG_ECS}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    build:
      context: .
      dockerfile: Dockerfile.ecr.common
      args:
        BASE_IMAGE: ${REG}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    environment:
      env_apigateway_configure_default_ignore_errors: "true"
      env_apigateway_configure_lb: "true"
      env_apigateway_configure_lb_ignore_errors: "false"
      env_apigateway_configure_extended_settings: "true"
      env_apigateway_configure_portalgateway: "true"
      env_apigateway_host: apigateway
      env_apigateway_port: "5555"
      env_apigateway_rest_user: Administrator
      env_apigateway_rest_password: "${SAG_PASSWORD}"
      env_apigateway_rest_password_old: "manage"
      env_apigateway_lb_http_url: "http://apigateway:5555"
      env_apigateway_lb_https_url: "https://apigateway:5543"
      env_apigateway_lb_websocket_url: "ws://apigateway"
      env_apigateway_lb_http_url_alt1: "http://apigateway:5555"
      env_apigateway_lb_https_url_alt1: "https://apigateway:5543"
      env_apigateway_lb_websocket_url_alt1: "ws://apigateway"
      env_apigateway_lb_webapp_url: "http://apigateway:9072"
      env_apigateway_portalgateway_gateway_url: "http://apigateway:5555"
      env_apigateway_portalgateway_gateway_username: "Administrator"
      env_apigateway_portalgateway_gateway_password: "${SAG_PASSWORD}"
      env_apigateway_portalgateway_portal_url: "https://apiportal:18102"
      env_apigateway_portalgateway_portal_username: "system"
      env_apigateway_portalgateway_portal_password: "manager"
    networks:
      - apigwnet