version: "3.2"

networks:
  testnet:

x-aws-vpc: ${TARGET_VPC}
x-aws-loadbalancer: ${TARGET_LOADBALANCER}

services:

  reverseproxy_nginx:
    image: nginx:stable-alpine
    ports:
      - target: 80
        x-aws-protocol: http
    networks:
      - testnet