version: "3.2"

networks:
  apigwnet:

x-aws-vpc: ${TARGET_VPC}
x-aws-loadbalancer: ${TARGET_LOADBALANCER}
x-aws-cluster: ${TARGET_ECS_CLUSTER}
x-aws-cloudformation:
  Resources:
    ReverseproxynginxTCP80TargetGroup:
      Properties:
        HealthCheckPath: /rest/apigateway/health
        Matcher:
          HttpCode: "200"
        TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '180'
        - Key: slow_start.duration_seconds
          Value: '300'
        - Key: load_balancing.algorithm.type
          Value: 'round_robin'          
        - Key: stickiness.enabled
          Value: 'true'
        - Key: stickiness.type
          Value: lb_cookie
        - Key: stickiness.lb_cookie.duration_seconds
          Value: '3600'

services:

  reverseproxy_nginx:
    image: ${REG_ECS}webmethods-apigateway-reverseproxy:${TAG_APIGATEWAY:-dev-10.7-latest}
    build:
      context: nginx
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - 80:80
    networks:
      - apigwnet
    depends_on:
      - apigateway

  apigateway:
    image: ${REG_ECS}webmethods-apigateway-standalone:${TAG_APIGATEWAY:-dev-10.7-latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${REG:-harbor.saggs.cloud/library/}webmethods-apigateway-standalone:${TAG_APIGATEWAY:-dev-10.7-latest}
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8192M
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment: 
      APIGW_ELASTICSEARCH_TENANTID: apigateway
      JAVA_MIN_MEM: 2g
      JAVA_MAX_MEM: 4g
      RUNTIME_WATT_PROPERTIES: "watt.net.timeout=400 watt.server.threadPool=800 watt.server.threadPoolMin=25 watt.net.maxClientKeepaliveConns=10"
    networks:
      - apigwnet
