cluster: 'myecstests' # The short name or full Amazon Resource Name (ARN) of the cluster on which to run your task.
count: 1 # The number of instantiations of the specified task to place on your cluster.
enableECSManagedTags: true # Specifies whether to enable Amazon ECS managed tags for the task.
group: 'apigateway-standalone-ecs-configurator' # The name of the task group to associate with the task.
launchType: FARGATE # The launch type on which to run your task. Valid values are: EC2, FARGATE.
networkConfiguration: # The network configuration for the task.
  awsvpcConfiguration:  # The VPC subnets and security groups associated with a task.
    subnets:  # [REQUIRED] The subnets associated with the task or service.
    - 'subnet-07e700c7d40852725'
    - 'subnet-0ebca36d96481e15e'
    - 'subnet-0c47347954c1717f4'
    securityGroups: # The security groups associated with the task or service.
    - 'sg-072e23e0b0fa51265'
    assignPublicIp: DISABLED # Whether the task's elastic network interface receives a public IP address. Valid values are: ENABLED, DISABLED.
platformVersion: '1.4.0' # The platform version the task should run.
propagateTags: TASK_DEFINITION # Specifies whether to propagate the tags from the task definition to the task. Valid values are: TASK_DEFINITION, SERVICE.