AWSTemplateFormatVersion: 2010-09-09
Metadata:
  Cluster: arn:aws:ecs:us-east-1:815840818766:cluster/myecstests
Resources:
  ApigatewayconfiguratorService:
    Properties:
      Cluster: arn:aws:ecs:us-east-1:815840818766:cluster/myecstests
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DeploymentController:
        Type: ECS
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
          - Ref: ApigwnetNetwork
          Subnets:
          - subnet-07e700c7d40852725
          - subnet-0c47347954c1717f4
          - subnet-0ebca36d96481e15e
      PlatformVersion: 1.4.0
      PropagateTags: SERVICE
      SchedulingStrategy: REPLICA
      ServiceRegistries:
      - RegistryArn:
          Fn::GetAtt:
          - ApigatewayconfiguratorServiceDiscoveryEntry
          - Arn
      Tags:
      - Key: com.docker.compose.project
        Value: apigateway-standalone-ecs
      - Key: com.docker.compose.service
        Value: apigateway_configurator
      TaskDefinition:
        Ref: ApigatewayconfiguratorTaskDefinition
    Type: AWS::ECS::Service
  ApigatewayconfiguratorServiceDiscoveryEntry:
    Properties:
      Description: '"apigateway_configurator" service discovery entry in Cloud Map'
      DnsConfig:
        DnsRecords:
        - TTL: 60
          Type: A
        RoutingPolicy: MULTIVALUE
      HealthCheckCustomConfig:
        FailureThreshold: 1
      Name: apigateway_configurator
      NamespaceId:
        Ref: CloudMap
    Type: AWS::ServiceDiscovery::Service
  ApigatewayconfiguratorTaskDefinition:
    Properties:
      ContainerDefinitions:
      - Command:
        - us-east-1.compute.internal
        - apigateway-standalone-ecs.local
        Essential: false
        Image: docker/ecs-searchdomain-sidecar:1.0
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group:
              Ref: LogGroup
            awslogs-region:
              Ref: AWS::Region
            awslogs-stream-prefix: apigateway-standalone-ecs
        Name: Apigatewayconfigurator_ResolvConf_InitContainer
      - DependsOn:
        - Condition: SUCCESS
          ContainerName: Apigatewayconfigurator_ResolvConf_InitContainer
        Environment:
        - Name: env_apigateway_configure_default_ignore_errors
          Value: "true"
        - Name: env_apigateway_configure_extended_settings
          Value: "true"
        - Name: env_apigateway_configure_lb
          Value: "true"
        - Name: env_apigateway_configure_lb_ignore_errors
          Value: "false"
        - Name: env_apigateway_configure_portalgateway
          Value: "true"
        - Name: env_apigateway_host
          Value: apigateway
        - Name: env_apigateway_lb_http_url
          Value: http://apigateway:5555
        - Name: env_apigateway_lb_http_url_alt1
          Value: http://apigateway:5555
        - Name: env_apigateway_lb_https_url
          Value: https://apigateway:5543
        - Name: env_apigateway_lb_https_url_alt1
          Value: https://apigateway:5543
        - Name: env_apigateway_lb_webapp_url
          Value: http://apigateway:9072
        - Name: env_apigateway_lb_websocket_url
          Value: ws://apigateway
        - Name: env_apigateway_lb_websocket_url_alt1
          Value: ws://apigateway
        - Name: env_apigateway_port
          Value: "5555"
        - Name: env_apigateway_portalgateway_gateway_password
          Value: somethingnew
        - Name: env_apigateway_portalgateway_gateway_url
          Value: http://apigateway:5555
        - Name: env_apigateway_portalgateway_gateway_username
          Value: Administrator
        - Name: env_apigateway_portalgateway_portal_password
          Value: manager
        - Name: env_apigateway_portalgateway_portal_url
          Value: https://apiportal:18102
        - Name: env_apigateway_portalgateway_portal_username
          Value: system
        - Name: env_apigateway_rest_password
          Value: somethingnew
        - Name: env_apigateway_rest_password_old
          Value: manage
        - Name: env_apigateway_rest_user
          Value: Administrator
        Essential: true
        Image: 815840818766.dkr.ecr.us-east-1.amazonaws.com/webmethods-apigateway-configurator:configurator-10.7.2-38@sha256:40d3450d41fe6b98795ee11b6c0d1708a2893734dca4ecf0088deb6b66672145
        LinuxParameters: {}
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group:
              Ref: LogGroup
            awslogs-region:
              Ref: AWS::Region
            awslogs-stream-prefix: apigateway-standalone-ecs
        Name: apigateway_configurator
      Cpu: "256"
      ExecutionRoleArn:
        Ref: ApigatewayconfiguratorTaskExecutionRole
      Family: apigateway-standalone-ecs-apigateway_configurator
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
      - FARGATE
    Type: AWS::ECS::TaskDefinition
  ApigatewayconfiguratorTaskExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Condition: {}
          Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      Tags:
      - Key: com.docker.compose.project
        Value: apigateway-standalone-ecs
      - Key: com.docker.compose.service
        Value: apigateway_configurator
    Type: AWS::IAM::Role
  ApigwnetNetwork:
    Properties:
      GroupDescription: apigateway-standalone-ecs Security Group for apigwnet network
      Tags:
      - Key: com.docker.compose.project
        Value: apigateway-standalone-ecs
      - Key: com.docker.compose.network
        Value: apigateway-standalone-ecs_apigwnet
      VpcId: vpc-0cecc9e7fa3bee3f1
    Type: AWS::EC2::SecurityGroup
  ApigwnetNetworkIngress:
    Properties:
      Description: Allow communication within network apigwnet
      GroupId:
        Ref: ApigwnetNetwork
      IpProtocol: "-1"
      SourceSecurityGroupId:
        Ref: ApigwnetNetwork
    Type: AWS::EC2::SecurityGroupIngress
  CloudMap:
    Properties:
      Description: Service Map for Docker Compose project apigateway-standalone-ecs
      Name: apigateway-standalone-ecs.local
      Vpc: vpc-0cecc9e7fa3bee3f1
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
  DefaultNetwork:
    Properties:
      GroupDescription: apigateway-standalone-ecs Security Group for default network
      Tags:
      - Key: com.docker.compose.project
        Value: apigateway-standalone-ecs
      - Key: com.docker.compose.network
        Value: apigateway-standalone-ecs_default
      VpcId: vpc-0cecc9e7fa3bee3f1
    Type: AWS::EC2::SecurityGroup
  DefaultNetworkIngress:
    Properties:
      Description: Allow communication within network default
      GroupId:
        Ref: DefaultNetwork
      IpProtocol: "-1"
      SourceSecurityGroupId:
        Ref: DefaultNetwork
    Type: AWS::EC2::SecurityGroupIngress
  LogGroup:
    Properties:
      LogGroupName: /docker-compose/apigateway-standalone-ecs
    Type: AWS::Logs::LogGroup
