version: "3.2"

networks:
  stack:

volumes:
  apiportal-data:

services:

  devportal:
    image: ${REG}webmethods-devportal:${TAG_PORTAL}
    ports:
      - "18101:18101"
      - "18102:18102"
    environment: 
      JAVA_MIN_MEM: 512m
      JAVA_MAX_MEM: 512m
      JAVA_OPTS: ""
      PORTAL_SERVER_CONFIG_TENANT: default
      PORTAL_SERVER_CONFIG_LICENSE: /opt/softwareag/licenseKey.xml
      SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
      SPRING_ELASTICSEARCH_REST_USERNAME: elastic
      SPRING_ELASTICSEARCH_REST_PASSWORD: password
    volumes:
      - ${PWD}/licensing/devportal-licenseKey.xml:/opt/softwareag/licenseKey.xml:ro
    hostname: devportal
    networks:
      - stack

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG_ELASTIC_VERSION}
    hostname: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=password
      - http.port=9200
      - transport.port=9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
      - stack