CREATE USER STREAMSETS IDENTIFIED BY STREAMSETS DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA 2000M on USERS CONTAINER=CURRENT;
GRANT ALL PRIVILEGES TO STREAMSETS;
CREATE TABLE STREAMSETS.EMPLOYEE (ID NUMBER(20,0) PRIMARY KEY, NAME VARCHAR2(255), ADDRESS VARCHAR2(255), REGION VARCHAR2(2), DEPT VARCHAR2(2));
INSERT INTO STREAMSETS.EMPLOYEE VALUES (1327, 'BRYAN FERRY', '123 Vine St', 'UK', 'RM');
INSERT INTO STREAMSETS.EMPLOYEE VALUES (1001, 'PATTI SMITH', '234 Vine St', 'NY', 'PS');
INSERT INTO STREAMSETS.EMPLOYEE VALUES (1002, 'ROBERT FRIPP', '345 Vine St', 'UK', 'RF');
commit;