version: "3.2"

networks:
  stack:

volumes:
  apiportal-data:

services:

  apigateway:
    image: ${REG}webmethods-apigateway-standalone:${TAG_APIGATEWAY}
    ports:
      - "5555:5555"
      - "9072:9072"
    environment: 
      APIGW_ELASTICSEARCH_TENANTID: apigateway
      JAVA_MIN_MEM: 1g
      JAVA_MAX_MEM: 2g
      JAVA_OPTS: "-Dtest2=test2 -Dtest3=test3 -Dtest4=test4"
      RUNTIME_WATT_PROPERTIES: "watt.net.timeout=400 watt.server.threadPool=800 watt.server.threadPoolMin=25 watt.net.maxClientKeepaliveConns=10 test.test=something=2"
    volumes:
      - ${PWD}/apigateway-licenseKey.xml:/opt/softwareag/IntegrationServer/instances/default/config/licenseKey.xml:rw
    hostname: apigateway
    networks:
      - stack

  apiportal:
    image: ${REG}webmethods-apiportal:${TAG_APIPORTAL}
    ports:
      - 18101:18101
    hostname: apiportal
    environment: 
      - DATA_ROOT_DIR=/data
      - TENANTMGT_SYSTEMUSER_PASSWORD=somethingnew
      - TENANTMGT_SUPERUSER_PASSWORD=somethingnew
    volumes:
      - ${PWD}/apiportal-licenseKey.xml:/opt/softwareag/API_Portal/license.xml:rw
      - apiportal-data:/data:rw
    networks:
      - stack

  webmethods-sample-apis-uszip:
    image: ${REG}webmethods-sample-apis-uszip:${TAG_SAMPLE_APIS}
    expose:
      - "7071"
    ports:
      - "7071:7071"
    networks:
      - stack

  webmethods-sample-apis-bookstore:
    image: ${REG}webmethods-sample-apis-bookstore:${TAG_SAMPLE_APIS}
    expose:
      - "7071"
    ports:
      - "7072:7071"
    networks:
      - stack

  apigateway_configurator:
    image: ${REG}webmethods-apigateway-configurator:${TAG_APIGATEWAY_CONFIGURATOR}
    command: ["-v","apply_configs.yaml"]
    environment:
      env_apigateway_configure_default_ignore_errors: "true"
      env_apigateway_configure_lb: "true"
      env_apigateway_configure_lb_ignore_errors: "false"
      env_apigateway_configure_extended_settings: "true"
      env_apigateway_configure_portalgateway: "true"
      env_apigateway_host: apigateway
      env_apigateway_port: "5555"
      env_apigateway_rest_user: Administrator
      env_apigateway_rest_password: "somethingnew"
      env_apigateway_rest_password_old: "manage"
      env_apigateway_lb_http_url: "http://external_access"
      env_apigateway_lb_https_url: "https://external_access"
      env_apigateway_lb_websocket_url: ""
      env_apigateway_lb_webapp_url: "http://external_access"
      env_apigateway_portalgateway_gateway_url: "http://apigateway:5555"
      env_apigateway_portalgateway_gateway_username: "Administrator"
      env_apigateway_portalgateway_gateway_password: "somethingnew"
      env_apigateway_portalgateway_portal_url: "http://apiportal:18101"
      env_apigateway_portalgateway_portal_username: "system"
      env_apigateway_portalgateway_portal_password: "somethingnew"
    networks:
      - stack