---

# ## SAG GOV image
# image:
#   registry: ghcr.io/softwareag-government-solutions
#   repository: devportal
#   pullPolicy: IfNotPresent
#   tag: 10.15

## SAG image
image:
  registry: sagcr.azurecr.io
  repository: devportal
  pullPolicy: IfNotPresent
  tag: "10.15"

imagePullSecrets:
  - name: sag-containers-repo

licenseSecret:
  name: softwareag-apimgt-licenses
  key: devportal-license
  path: license.xml

replicaCount: 2

resources:
  requests:
    memory: 1Gi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: 1

service:
  port: 8084
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"

settings:
  tenant: default
  profile: dev
  loadbalancerUrl: http://devportal.domain.local/portal/
  javaMemMin: 256m
  javaMemMax: 512m
  javaOpts: "-XX:+DisableExplicitGC"
  clustering:
    enabled: true
  elastic:
    uris: http://elasticsearch-es-http:9200

waitforelastic:
  enabled: true
  uri: http://elasticsearch-es-http:9200

# UI ingress
ingress:
  enabled: true
  className: traefik-external
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: webmethods-devportal.domain.local
      paths:
        - path: /
          pathType: Prefix
