version: "3.2"

networks:
  stack:

volumes:
  apip-postgresdata:
  apip-elasticdata:
  apip-cloudsearchdata:

services:

  apiportal:
    image: ${REG}webmethods-apiportal:${TAG_APIPORTAL}
    ports:
      - 18101:18101
    hostname: apiportal
    volumes:
      - ${PWD}/licensing/apiportal-licenseKey.xml:/opt/softwareag/API_Portal/license.xml:rw
      - apip-postgresdata:/opt/softwareag/API_Portal/server/bin/work/work_postgres_m/data:rw
      - apip-elasticdata:/opt/softwareag/API_Portal/server/bin/work/work_elastic_m/data:rw
      - apip-cloudsearchdata:/opt/softwareag/API_Portal/server/bin/work/work_cloudsearch_m/rsindex:rw
    networks:
      - stack