version: "3.2"

networks:
  stack:

volumes:
  data1:
  backup1:
  index1:

services:

  caching_client:
    image: ${REG}sample-caching-client:${TAG_BIGMEMORY}
    build:
      context: ../sample-ehcache-client
      dockerfile: Dockerfile
      args:
        BIGMEMORY_KIT_URL: ${BIGMEMORY_KIT_URL}
        BIGMEMORY_KIT_BASEDIR: ${BIGMEMORY_KIT_BASEDIR}
    environment:
      - LICENSE_FILE=/var/run/terracotta-license.key
      - TERRACOTTA_SERVER_URL=terracotta:9510
    volumes:
      - ../licensing/terracotta-license.key:/var/run/terracotta-license.key:ro
    networks:
      - stack

  terracotta:
    image: ${REG}${REPO_BIGMEMORY}:${TAG_BIGMEMORY}
    hostname: terracotta
    environment: 
      - LICENSE_FILE=/var/run/terracotta-license.key
      - TSA_PORT=9510
      - JMX_PORT=9520
      - GROUP_PORT=9530
      - MGT_PORT=9540
      - HEAP_SIZE_MB_MIN=512m
      - HEAP_SIZE_MB_MAX=1024m
      - DATA_STORAGE_SIZE=20g
      - DATA_OFFHEAP_SIZE=1g
      - RESTARTABLE_ENABLED=false
    volumes:
      - ../licensing/terracotta-license.key:/var/run/terracotta-license.key:ro
      - data1:/opt/softwareag/Terracotta/data/diskstore:rw
      - backup1:/opt/softwareag/Terracotta/data/backup:rw
      - index1:/opt/softwareag/Terracotta/data/index:rw
    networks:
      - stack

  tmc:
    image: ${REG}${REPO_BIGMEMORY_MGTSERVER}:${TAG_BIGMEMORY}
    ports:
      - 9889:9889
      - 9443:9443
    environment: 
      - LICENSE_FILE=/var/run/terracotta-license.key
    volumes:
      - ../licensing/terracotta-license.key:/var/run/terracotta-license.key:ro
    hostname: tmc
    networks:
      - stack