---

image:
  repository: 815840818766.dkr.ecr.us-east-1.amazonaws.com/webmethods-apigateway
  tag: dev-10.11-latest

replicaCount: 2

envConfigs:
  JAVA_MIN_MEM: 1g
  JAVA_MAX_MEM: 2g
  JAVA_OPTS: ""
  RUNTIME_WATT_PROPERTIES: watt.server.cachemanager.connectTimeout=300000 watt.server.threadPoolMin=10 watt.server.threadPool=500 watt.server.control.serverThreadThreshold=20 watt.net.timeout=400 watt.security.ssl.cacheClientSessions=true watt.net.maxClientKeepaliveConns=10 watt.security.ssl.resumeClientSessions=true
  APIGW_ELASTICSEARCH_TENANTID: apigateway
  APIGW_ELASTICSEARCH_HOSTS: elasticsearch-es-sag-apidatastore:9200
  APIGW_KIBANA_DASHBOARDINSTANCE: http://kibana-kb-http:5601
  APIGW_ELASTICSEARCH_HTTP_USERNAME: elastic
  CLUSTER_AWARE: true
  CLUSTER_NAME: APIGatewayTSAcluster
  CLUSTER_TSAURLS: webmethods-terracotta-0.webmethods-terracotta-hl:9510,webmethods-terracotta-1.webmethods-terracotta-hl:9510
  CLUSTER_SESSTIMEOUT: 30
  CLUSTER_ACTIONONSTARTUPERROR: shutdown
  CLUSTER_CONNECTTIMEOUT: 30000
  HEALTHCHECK_ELASTIC_USER: elastic

envSecretConfigs:
  APIGW_ELASTICSEARCH_HTTP_PASSWORD:
    secretKeyRef: elasticsearch-es-elastic-user
    key: elastic
  HEALTHCHECK_ELASTIC_PASSWORD:
    secretKeyRef: elasticsearch-es-elastic-user
    key: elastic

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50

# apply stickiness for the UI ingress
service:
  gwui:
    annotations:
      traefik.ingress.kubernetes.io/service.sticky.cookie: "true"

# Runtime ingress: runtime path are /gateway, /rest, /invoke, /WmAPIGateway
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: webmethods-apigateway.cluster-demo.apimgt.saggov
      paths:
        - path: /gateway
          pathType: Prefix
          backendServiceName: webmethods-apigateway-gwruntime
          backendServicePort: 5555
        - path: /rest
          pathType: Prefix
          backendServiceName: webmethods-apigateway-gwruntime
          backendServicePort: 5555
        - path: /invoke
          pathType: Prefix
          backendServiceName: webmethods-apigateway-gwruntime
          backendServicePort: 5555
        - path: /WmAPIGateway
          pathType: Prefix
          backendServiceName: webmethods-apigateway-gwruntime
          backendServicePort: 5555
        - path: /
          pathType: Prefix
          backendServiceName: webmethods-apigateway-gwui
          backendServicePort: 9072