version: "3.2"

networks:
  stack:

services:

  caching_client:
    image: ${REG}webmethods-terracotta/sample-caching-client:${TAG_TERRACOTTA}
    build:
      context: ../sample-ehcache-client
      dockerfile: Dockerfile
      args:
        BUILDER_IMAGE: ${REG}webmethods-terracotta:${TAG_TERRACOTTA}
    environment:
      - LICENSE_FILE=/var/run/terracotta-license.key
      - TERRACOTTA_SERVER_URL=terracotta:9510
    volumes:
      - ${PWD}/licensing/terracotta-license.key:/var/run/terracotta-license.key:ro
    networks:
      - stack

  terracotta:
    image: ${REG}webmethods-terracotta:${TAG_TERRACOTTA}
    environment: 
      - LICENSE_FILE=/var/run/terracotta-license.key
    volumes:
      - ${PWD}/licensing/terracotta-license.key:/var/run/terracotta-license.key:ro
    hostname: terracotta
    networks:
      - stack

  tmc:
    image: ${REG}webmethods-terracotta-tmc:${TAG_TERRACOTTA}
    ports:
      - 9889:9889
      - 9443:9443
    environment: 
      - LICENSE_FILE=/var/run/terracotta-license.key
    volumes:
      - ${PWD}/licensing/terracotta-license.key:/var/run/terracotta-license.key:ro
    hostname: tmc
    networks:
      - stack