version: "3.2"

networks:
  stack:

volumes:
  esdata:
    driver: local

services:

  lbnginx:
    image: apigateway-reverseproxy:${TAG_APIGATEWAY}
    build:
      context: ../../common/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ./nginx/apigateway.conf:/etc/nginx/sites-enabled/apigateway.conf:ro
      - ./nginx/devportal.conf:/etc/nginx/sites-enabled/devportal.conf:ro
    networks:
      - stack
    depends_on: 
      - apigateway1
      - apigateway2
      - devportal1
      - devportal2

  apigateway1:
    image: ${REG_APIGATEWAY}${REPO_APIGATEWAY}:${TAG_APIGATEWAY}
    ports:
      - 5555:5555
      - 9072:9072
    environment: 
      JAVA_MIN_MEM: 1g
      JAVA_MAX_MEM: 1g
      JAVA_OPTS: ""
      apigw_elasticsearch_tenantId: ${TENANTID}
      apigw_elasticsearch_hosts: elasticsearch:9200
      apigw_elasticsearch_autostart: "false"
      apigw_elasticsearch_https_enabled: "false"
      apigw_kibana_dashboardInstance: http://kibana:5601
      apigw_kibana_autostart: "false"
      apigw_cluster_ignite_hostnames: apigateway1,apigateway2
    volumes:
      - ./configs:/opt/softwareag/IntegrationServer/instances/default/packages/WmAPIGateway/resources/configuration:ro
      - ../licensing/apigateway-licenseKey.xml:/opt/softwareag/IntegrationServer/instances/default/config/licenseKey.xml:rw
    networks:
      - stack
    depends_on: 
      - elasticsearch

  apigateway2:
    image: ${REG_APIGATEWAY}${REPO_APIGATEWAY}:${TAG_APIGATEWAY}
    ports:
      - 6555:5555
      - 10072:9072
    environment: 
      JAVA_MIN_MEM: 1g
      JAVA_MAX_MEM: 1g
      JAVA_OPTS: ""
      apigw_elasticsearch_tenantId: ${TENANTID}
      apigw_elasticsearch_hosts: elasticsearch:9200
      apigw_elasticsearch_autostart: "false"
      apigw_elasticsearch_https_enabled: "false"
      apigw_kibana_dashboardInstance: http://kibana:5601
      apigw_kibana_autostart: "false"
      apigw_cluster_ignite_hostnames: apigateway1,apigateway2
    volumes:
      - ./configs:/opt/softwareag/IntegrationServer/instances/default/packages/WmAPIGateway/resources/configuration:ro
      - ../licensing/apigateway-licenseKey.xml:/opt/softwareag/IntegrationServer/instances/default/config/licenseKey.xml:rw
    networks:
      - stack
    depends_on: 
      - elasticsearch

  devportal1:
    image: ${REG_DEVPORTAL}${REPO_DEVPORTAL}:${TAG_DEVPORTAL}
    ports:
      - 8083:8083
      - 8084:8084
    environment: 
      JAVA_MIN_MEM: 256m
      JAVA_MAX_MEM: 256m
      JAVA_OPTS: "-XX:+DisableExplicitGC"
      SPRING_ELASTICSEARCH_REST_URIS: "http://elasticsearch:9200"
      PORTAL_SERVER_CONFIG_LICENSE: "/opt/softwareag/licenseKey.xml"
      PORTAL_SERVER_CACHE_DISTRIBUTED_ENABLED: "true"
      PORTAL_SERVER_CACHE_DISTRIBUTED_CLUSTER_PEERS_0: "devportal1:47500..47509"
      PORTAL_SERVER_CACHE_DISTRIBUTED_CLUSTER_PEERS_1: "devportal2:47500..47509"
      PORTAL_SERVER_UMC_LB_URL: http://lbnginx:81/portal/
    volumes:
      -  ../licensing/devportal-licenseKey.xml:/opt/softwareag/licenseKey.xml:ro
    networks:
      - stack
    depends_on: 
      - elasticsearch

  devportal2:
    image: ${REG_DEVPORTAL}${REPO_DEVPORTAL}:${TAG_DEVPORTAL}
    ports:
      - 18083:8083
      - 18084:8084
    environment: 
      JAVA_MIN_MEM: 256m
      JAVA_MAX_MEM: 256m
      JAVA_OPTS: "-XX:+DisableExplicitGC"
      SPRING_ELASTICSEARCH_REST_URIS: "http://elasticsearch:9200"
      PORTAL_SERVER_CONFIG_LICENSE: "/opt/softwareag/licenseKey.xml"
      PORTAL_SERVER_CACHE_DISTRIBUTED_ENABLED: "true"
      PORTAL_SERVER_CACHE_DISTRIBUTED_CLUSTER_PEERS_0: "devportal1:47500..47509"
      PORTAL_SERVER_CACHE_DISTRIBUTED_CLUSTER_PEERS_1: "devportal2:47500..47509"
      PORTAL_SERVER_UMC_LB_URL: http://lbnginx:81/portal/
    volumes:
      - ../licensing/devportal-licenseKey.xml:/opt/softwareag/licenseKey.xml:rw
    networks:
      - stack
    depends_on: 
      - elasticsearch
  
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: ${IMAGE_ELASTIC}:${TAG_ELASTIC}
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - http.port=9200
      - transport.port=9300
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
      - stack

  kibana:
    image: ${IMAGE_KIBANA}:${TAG_ELASTIC}
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      SERVER_HOST: 0.0.0.0
      SERVER_BASEPATH: /apigatewayui/dashboardproxy
      NODE_OPTIONS: --max_old_space_size=2048
    links:
      - elasticsearch
    networks:
      - stack
    depends_on: 
      - elasticsearch

  configurator_apigateway:
    image: ${REG_APIGATEWAY_CONFIGURATOR}${REPO_APIGATEWAY_CONFIGURATOR}:${TAG_APIGATEWAY_CONFIGURATOR}
    environment: 
      connect_host: apigateway1
      connect_port: "5555"
      connect_user: Administrator
      connect_password: "somethingnew"
      changepassword_enabled: "true"
      changepassword_old: "manage"
      settings_lburls_configure: "true"
      settings_lburls_http_urls: "http://localhost;http://lbnginx"
      settings_lburls_https_urls: ""
      settings_lburls_websocket_url: "ws://localhost"
      settings_lburls_webapp_url: "http://localhost"
      settings_portalgateway_configure: "true"
      settings_portalgateway_name: API PortalGateway Config
      settings_portalgateway_description: API PortalGateway Configuration
      settings_portalgateway_version: "1.0"
      settings_portalgateway_stagename: "DEV"
      settings_portalgateway_gateway_url: "http://lbnginx"
      settings_portalgateway_gateway_username: "Administrator"
      settings_portalgateway_gateway_password: "somethingnew"
      settings_portalgateway_portaltype: devportal
      settings_portalgateway_devportal_tenant: "default"
      settings_portalgateway_devportal_url: "http://lbnginx:81/portal"
      settings_portalgateway_devportal_username: "Administrator"
      settings_portalgateway_devportal_password: "somethingnew"
      settings_core_configure: "true"
      settings_core_watts: watt.server.cachemanager.connectTimeout=300000 watt.net.timeout=600 watt.net.clientKeepaliveUsageLimit=10000000 watt.server.threadPoolMin=50 watt.server.threadPool=1000 watt.server.control.serverThreadThreshold=50 watt.security.ssl.cacheClientSessions=true watt.net.maxClientKeepaliveConns=500 watt.security.ssl.resumeClientSessions=true
      settings_core_extended: "events.reportingQueue.size=5000 events.collectionPool.minThreads=2 events.collectionPool.maxThreads=32 events.reportingPool.minThreads=4 events.reportingPool.maxThreads=16 eventsRefreshInterval=60s events.collectionQueue.size=10000000"
    networks:
      - stack

  configurator_devportal:
    image: ${REG_DEVPORTAL_CONFIGURATOR}${REPO_DEVPORTAL_CONFIGURATOR}:${TAG_DEVPORTAL_CONFIGURATOR}
    environment: 
      connect_host: devportal1
      connect_port: "8083"
      connect_user: Administrator
      connect_password: "somethingnew"
      changepassword_enabled: "true"
      changepassword_old: "manage"
      settings_loadbalancerurl_configure: "true"
      settings_loadbalancerurl_value: "http://lbnginx:81/portal/"
    networks:
      - stack