version: "3.2"

networks:
  stack:

volumes:
  esdata:
    driver: local

services:

  devportal1:
    image: ${REG}devportal:${TAG_DEVPORTAL}
    ports:
      - 8083:8083
      - 8084:8084
    environment: 
      JAVA_MIN_MEM: 1g
      JAVA_MAX_MEM: 1g
      JAVA_OPTS: "-XX:MaxDirectMemorySize=10g -XX:+DisableExplicitGC"
      SPRING_ELASTICSEARCH_REST_URIS: "http://elasticsearch:9200"
      PORTAL_SERVER_CONFIG_LICENSE: "/opt/softwareag/licenseKey.xml"
      PORTAL_SERVER_CACHE_DISTRIBUTED_ENABLED: "true"
      PORTAL_SERVER_CACHE_DISTRIBUTED_CLUSTER_PEERS_0: "devportal1:47500..47509"
      PORTAL_SERVER_CACHE_DISTRIBUTED_CLUSTER_PEERS_1: "devportal2:47500..47509"
      PORTAL_SERVER_CONFIG_TENANT: "${TENANTID}"
    volumes:
      - ../resources/licensing/devportal-licenseKey.xml:/opt/softwareag/licenseKey.xml:ro
    hostname: devportal
    networks:
      - stack
    depends_on: 
      - elasticsearch

  devportal2:
    image: ${REG}devportal:${TAG_DEVPORTAL}
    ports:
      - 18083:8083
      - 18084:8084
    environment: 
      JAVA_MIN_MEM: 1g
      JAVA_MAX_MEM: 1g
      JAVA_OPTS: "-XX:MaxDirectMemorySize=10g -XX:+DisableExplicitGC"
      SPRING_ELASTICSEARCH_REST_URIS: "http://elasticsearch:9200"
      PORTAL_SERVER_CONFIG_LICENSE: "/opt/softwareag/licenseKey.xml"
      PORTAL_SERVER_CACHE_DISTRIBUTED_ENABLED: "true"
      PORTAL_SERVER_CACHE_DISTRIBUTED_CLUSTER_PEERS_0: "devportal1:47500..47509"
      PORTAL_SERVER_CACHE_DISTRIBUTED_CLUSTER_PEERS_1: "devportal2:47500..47509"
      PORTAL_SERVER_CONFIG_TENANT: "${TENANTID}"
    volumes:
      - ../licensing/devportal-licenseKey.xml:/opt/softwareag/licenseKey.xml:rw
    hostname: devportal
    networks:
      - stack
    depends_on: 
      - elasticsearch
  
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$TAG_ELASTIC_VERSION
    # image: docker.elastic.co/elasticsearch/elasticsearch-oss:$TAG_ELASTIC_VERSION
    hostname: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - http.port=9200
      - transport.port=9300
    volumes:
      - esdata:/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - stack