version: "3.9"

networks:
  stack:

volumes:
  esdata:
    driver: local

services:
  
  apigateway1:
    image: ${REG_APIGATEWAY}${REPO_APIGATEWAY}:${TAG_APIGATEWAY}
    ports:
      - 5555:5555
      - 9072:9072
    environment: 
      JAVA_MIN_MEM: 1g
      JAVA_MAX_MEM: 1g
      JAVA_OPTS: ""
      apigw_elasticsearch_tenantId: ${TENANTID}
      apigw_elasticsearch_hosts: elasticsearch:9200
      apigw_elasticsearch_autostart: "false"
      apigw_elasticsearch_https_enabled: "false"
      apigw_kibana_dashboardInstance: http://kibana:5601
      apigw_kibana_autostart: "false"
      apigw_cluster_tsaUrls: terracotta1:9510,terracotta2:9510
    volumes:
      - ./configs:/opt/softwareag/IntegrationServer/instances/default/packages/WmAPIGateway/resources/configuration:ro
      - ../licensing/apigateway-licenseKey.xml:/opt/softwareag/IntegrationServer/instances/default/config/licenseKey.xml:rw
      - ../licensing/terracotta-license.key:/opt/softwareag/common/conf/terracotta-license.key:ro
    hostname: apigateway1
    networks:
      - stack
    depends_on: 
      - elasticsearch

  apigateway2:
    image: ${REG_APIGATEWAY}${REPO_APIGATEWAY}:${TAG_APIGATEWAY}
    ports:
      - 6555:5555
      - 10072:9072
    environment: 
      JAVA_MIN_MEM: 1g
      JAVA_MAX_MEM: 1g
      JAVA_OPTS: ""
      apigw_elasticsearch_tenantId: ${TENANTID}
      apigw_elasticsearch_hosts: elasticsearch:9200
      apigw_elasticsearch_autostart: "false"
      apigw_elasticsearch_https_enabled: "false"
      apigw_kibana_dashboardInstance: http://kibana:5601
      apigw_kibana_autostart: "false"
      apigw_cluster_tsaUrls: terracotta1:9510,terracotta2:9510
    volumes:
      - ./configs:/opt/softwareag/IntegrationServer/instances/default/packages/WmAPIGateway/resources/configuration:ro
      - ../licensing/apigateway-licenseKey.xml:/opt/softwareag/IntegrationServer/instances/default/config/licenseKey.xml:rw
      - ../licensing/terracotta-license.key:/opt/softwareag/common/conf/terracotta-license.key:ro
    hostname: apigateway2
    networks:
      - stack
    depends_on: 
      - elasticsearch

  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: ${IMAGE_ELASTIC}:${TAG_ELASTIC}
    hostname: elasticsearch
    expose:
      - "9200"
      - "9300"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - http.port=9200
      - transport.port=9300
    volumes:
      - esdata:/data
    mem_limit: 2gb
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
      - stack

  kibana:
    image: ${IMAGE_KIBANA}:${TAG_KIBANA}
    hostname: kibana
    expose:
      - "5601"
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      SERVER_HOST: 0.0.0.0
      SERVER_BASEPATH: /apigatewayui/dashboardproxy
      NODE_OPTIONS: --max_old_space_size=2048
    mem_limit: 1gb
    links:
      - elasticsearch
    networks:
      - stack
    depends_on: 
      - elasticsearch

  terracotta1:
    image: ${REG_BIGMEMORY}${REPO_BIGMEMORY}:${TAG_BIGMEMORY}
    hostname: terracotta1
    expose:
      - "9510"
      - "9520"
      - "9530"
      - "9540"
    volumes:
      - ./tc-configs/tc-config.xml:/opt/softwareag/config/tc-config.xml:ro
      - ../licensing/terracotta-license.key:/opt/softwareag/config/license.key:ro
    networks:
      - stack

  terracotta2:
    image: ${REG_BIGMEMORY}${REPO_BIGMEMORY}:${TAG_BIGMEMORY}
    hostname: terracotta2
    expose:
      - "9510"
      - "9520"
      - "9530"
      - "9540"
    volumes:
      - ./tc-configs/tc-config.xml:/opt/softwareag/config/tc-config.xml:ro
      - ../licensing/terracotta-license.key:/opt/softwareag/config/license.key:ro
    networks:
      - stack
