---

imageTag: 8.2.3
elasticsearchHosts: "https://elasticsearch-master:9200"

kibanaConfig:
  kibana.yml: |
    server.basePath: /apigatewayui/dashboardproxy
    server.rewriteBasePath: false

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1
    memory: 1Gi