version: "3.2"

networks:
  stack:

volumes:
  data1:
  backup1:
  index1:
  data2:
  backup2:
  index2:
 
services:

  caching_client:
    image: ${REG:-harbor.saggs.cloud/library/}webmethods-terracotta/sample-caching-client:${TAG_TERRACOTTA:-dev-4.3.9-latest}
    build:
      context: ../sample-ehcache-client
      dockerfile: Dockerfile
      args:
        BUILDER_IMAGE: ${REG:-harbor.saggs.cloud/library/}webmethods-terracotta:${TAG_TERRACOTTA:-dev-4.3.9-latest}
    volumes:
      - ${PWD}/terracotta-license.key:/var/run/terracotta-license.key:ro
    environment: 
      - LICENSE_FILE=/var/run/terracotta-license.key
      - TERRACOTTA_SERVER_URL=terracotta1:9510,terracotta2:9510
      - JAVA_OPTS=-Dcom.tc.tc.config.total.timeout=60000
    networks:
      - stack
      
  terracotta1:
    image: ${REG:-harbor.saggs.cloud/library/}webmethods-terracotta:${TAG_TERRACOTTA:-dev-4.3.9-latest}
    hostname: terracotta1
    volumes:
      - ${PWD}/terracotta-license.key:/var/run/terracotta-license.key:ro
    environment:
      - LICENSE_FILE=/var/run/terracotta-license.key
      - TSA_PORT="9510"
      - JMX_PORT="9520"
      - GROUP_PORT="9530"
      - MGT_PORT="9540"
      - HEAP_SIZE_MB_MIN="512m"
      - HEAP_SIZE_MB_MAX="1024m"
      - DATA_STORAGE_SIZE="20g"
      - DATA_OFFHEAP_SIZE="1g"
      - RESTARTABLE_ENABLED="false"
      - TC_SERVER_HOST1="terracotta1"
      - TC_SERVER_HOST2="terracotta2"
    volumes:
      - ${PWD}/terracotta-license.key:/var/run/terracotta-license.key:ro
      - data1:/opt/softwareag/Terracotta/data/diskstore:rw
      - backup1:/opt/softwareag/Terracotta/data/backup:rw
      - index1:/opt/softwareag/Terracotta/data/index:rw
    networks:
      - stack

  terracotta2:
    image: ${REG:-harbor.saggs.cloud/library/}webmethods-terracotta:${TAG_TERRACOTTA:-dev-4.3.9-latest}
    hostname: terracotta2
    volumes:
      - ${PWD}/terracotta-license.key:/var/run/terracotta-license.key:ro
    environment:
      - LICENSE_FILE=/var/run/terracotta-license.key
      - TSA_PORT="9510"
      - JMX_PORT="9520"
      - GROUP_PORT="9530"
      - MGT_PORT="9540"
      - HEAP_SIZE_MB_MIN="512m"
      - HEAP_SIZE_MB_MAX="1024m"
      - DATA_STORAGE_SIZE="20g"
      - DATA_OFFHEAP_SIZE="1g"
      - RESTARTABLE_ENABLED="false"
      - TC_SERVER_HOST1="terracotta1"
      - TC_SERVER_HOST2="terracotta2"
    volumes:
      - ${PWD}/terracotta-license.key:/var/run/terracotta-license.key:ro
      - data2:/opt/softwareag/Terracotta/data/diskstore:rw
      - backup2:/opt/softwareag/Terracotta/data/backup:rw
      - index2:/opt/softwareag/Terracotta/data/index:rw
    networks:
      - stack

  tmc:
    image: ${REG:-harbor.saggs.cloud/library/}webmethods-terracotta-tmc:${TAG_TERRACOTTA:-dev-4.3.9-latest}
    ports:
      - 9889:9889
      - 9443:9443
    environment:
      - LICENSE_FILE=/var/run/terracotta-license.key
    volumes:
      - ${PWD}/terracotta-license.key:/var/run/terracotta-license.key:ro
    hostname: tmc
    networks:
      - stack