version: "3.2"

networks:
  stack:

volumes:
  data1:
  backup1:
  index1:
  data2:
  backup2:
  index2:
 
services:

  caching_client:
    image: sample-caching-client:${TAG_BIGMEMORY}
    build:
      context: ../sample-ehcache-client
      dockerfile: Dockerfile
      args:
        BIGMEMORY_KIT_URL: ${BIGMEMORY_KIT_URL}
        BIGMEMORY_KIT_BASEDIR: ${BIGMEMORY_KIT_BASEDIR}
    volumes:
      - ../licensing/terracotta-license.key:/var/run/terracotta-license.key:ro
    environment: 
      - LICENSE_FILE=/var/run/terracotta-license.key
      - TERRACOTTA_SERVER_URL=terracotta1:9510,terracotta2:9510
      - JAVA_OPTS=-Dcom.tc.tc.config.total.timeout=60000
    networks:
      - stack

  tmc:
    image: ${REG_BIGMEMORY}${REPO_BIGMEMORY_MGTSERVER}:${TAG_BIGMEMORY}
    ports:
      - 9889:9889
      - 9443:9443
    hostname: tmc
    volumes:
      - ../licensing/terracotta-license.key:/opt/softwareag/config/license.key:ro
    networks:
      - stack

  terracotta1:
    image: ${REG_BIGMEMORY}${REPO_BIGMEMORY}_volume_data:${TAG_BIGMEMORY}
    build:
      context: ../terracotta_volume_data
      dockerfile: Dockerfile
      args:
        REG_BIGMEMORY: ${REG_BIGMEMORY}
        REPO_BIGMEMORY: ${REPO_BIGMEMORY}
        TAG_BIGMEMORY: ${TAG_BIGMEMORY}
    hostname: terracotta1
    expose:
      - "9510"
      - "9520"
      - "9530"
      - "9540"
    volumes:
      - ./tc-configs/tc-config.xml:/opt/softwareag/config/tc-config.xml:ro
      - ../licensing/terracotta-license.key:/opt/softwareag/config/license.key:ro
      - data1:/data:rw
      - backup1:/backup:rw
      - index1:/index:rw
    networks:
      - stack

  terracotta2:
    image: ${REG_BIGMEMORY}${REPO_BIGMEMORY}_volume_data:${TAG_BIGMEMORY}
    build:
      context: ../terracotta_volume_data
      dockerfile: Dockerfile
      args:
        REG_BIGMEMORY: ${REG_BIGMEMORY}
        REPO_BIGMEMORY: ${REPO_BIGMEMORY}
        TAG_BIGMEMORY: ${TAG_BIGMEMORY}
    hostname: terracotta2
    expose:
      - "9510"
      - "9520"
      - "9530"
      - "9540"
    volumes:
      - ./tc-configs/tc-config.xml:/opt/softwareag/config/tc-config.xml:ro
      - ../licensing/terracotta-license.key:/opt/softwareag/config/license.key:ro
      - data2:/data:rw
      - backup2:/backup:rw
      - index2:/index:rw
    networks:
      - stack

  # terracotta1_data:
  #   image: terracotta_data
  #   build:
  #     context: ../terracotta_volume_data
  #     dockerfile: Dockerfile
  #     args:
  #       BIGMEMORY_KIT_URL: https://d2zwv9pap9ylyd.cloudfront.net/bigmemory-max-4.4.0.0.0.tar.gz
  #       BIGMEMORY_KIT_BASEDIR: /libs/bigmemory-max-4.4.0.0.0
  #   volumes:
  #     - data1:/data:rw
  #     - backup1:/backup:rw
  #     - index1:/index:rw
  #   networks:
  #     - stack
