---

api_endpoint:
  base_path: "/gateway"
admin_api:
  user: admin
  password: password
  admin_path: "/rest/microgateway"
applications_sync:
  enabled: true
  applications_to_sync: registeredApplications
  polling_interval_secs: 10
  connection_timeout_secs: 10
