version: "3.9"

networks:
  stack:

volumes:
  esdata:
    driver: local

services:
  
  apigateway1:
    image: ${REG_APIGATEWAY}${REPO_APIGATEWAY}:${TAG_APIGATEWAY}
    ports:
      - 5555:5555
      - 9072:9072
    environment: 
      JAVA_MIN_MEM: 1g
      JAVA_MAX_MEM: 1g
      JAVA_OPTS: ""
      apigw_elasticsearch_tenantId: tenant1
      apigw_elasticsearch_hosts: elasticsearch:9200
      apigw_elasticsearch_autostart: "false"
      apigw_elasticsearch_https_enabled: "false"
      apigw_kibana_dashboardInstance: http://kibana1:5601
      apigw_kibana_autostart: "false"
    volumes:
      - ./configs:/opt/softwareag/IntegrationServer/instances/default/packages/WmAPIGateway/resources/configuration:ro
      - ../licensing/apigateway-licenseKey.xml:/opt/softwareag/IntegrationServer/instances/default/config/licenseKey.xml:rw
    hostname: apigateway1
    mem_limit: 3gb
    links:
      - elasticsearch
      - kibana1
    networks:
      - stack
    depends_on: 
      - elasticsearch

  kibana1:
    image: ${IMAGE_KIBANA}:${TAG_KIBANA}
    hostname: kibana1
    expose:
      - "5601"
    environment:
      SERVER_NAME: kibana1
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      SERVER_HOST: 0.0.0.0
      SERVER_BASEPATH: /apigatewayui/dashboardproxy
      NODE_OPTIONS: --max_old_space_size=1024
    mem_limit: 1gb
    links:
      - elasticsearch
    networks:
      - stack
    depends_on:
      - elasticsearch
  
  apigateway2:
    image: ${REG_APIGATEWAY}${REPO_APIGATEWAY}:${TAG_APIGATEWAY}
    ports:
      - 6555:5555
      - 10072:9072
    environment: 
      JAVA_MIN_MEM: 1g
      JAVA_MAX_MEM: 1g
      JAVA_OPTS: ""
      apigw_elasticsearch_tenantId: tenant2
      apigw_elasticsearch_hosts: elasticsearch:9200
      apigw_elasticsearch_autostart: "false"
      apigw_elasticsearch_https_enabled: "false"
      apigw_kibana_dashboardInstance: http://kibana2:5601
      apigw_kibana_autostart: "false"
    volumes:
      - ./configs:/opt/softwareag/IntegrationServer/instances/default/packages/WmAPIGateway/resources/configuration:ro
      - ../licensing/apigateway-licenseKey.xml:/opt/softwareag/IntegrationServer/instances/default/config/licenseKey.xml:rw
    hostname: apigateway2
    mem_limit: 3gb
    links:
      - elasticsearch
      - kibana2
    networks:
      - stack
    depends_on: 
      - elasticsearch

  kibana2:
    image: ${IMAGE_KIBANA}:${TAG_KIBANA}
    hostname: kibana2
    expose:
      - "5601"
    environment:
      SERVER_NAME: kibana2
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      SERVER_HOST: 0.0.0.0
      SERVER_BASEPATH: /apigatewayui/dashboardproxy
      NODE_OPTIONS: --max_old_space_size=1024
    mem_limit: 1gb
    links:
      - elasticsearch
    networks:
      - stack
    depends_on: 
      - elasticsearch

  apigateway3:
    image: ${REG_APIGATEWAY}${REPO_APIGATEWAY}:${TAG_APIGATEWAY}
    ports:
      - 7555:5555
      - 11072:9072
    environment: 
      JAVA_MIN_MEM: 1g
      JAVA_MAX_MEM: 1g
      JAVA_OPTS: ""
      apigw_elasticsearch_tenantId: tenant3
      apigw_elasticsearch_hosts: elasticsearch:9200
      apigw_elasticsearch_autostart: "false"
      apigw_elasticsearch_https_enabled: "false"
      apigw_kibana_dashboardInstance: http://kibana3:5601
      apigw_kibana_autostart: "false"
    volumes:
      - ./configs:/opt/softwareag/IntegrationServer/instances/default/packages/WmAPIGateway/resources/configuration:ro
      - ../licensing/apigateway-licenseKey.xml:/opt/softwareag/IntegrationServer/instances/default/config/licenseKey.xml:rw
    hostname: apigateway3
    mem_limit: 3gb
    links:
      - elasticsearch
      - kibana3
    networks:
      - stack
    depends_on: 
      - elasticsearch

  kibana3:
    image: ${IMAGE_KIBANA}:${TAG_KIBANA}
    hostname: kibana3
    expose:
      - "5601"
    environment:
      SERVER_NAME: kibana3
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      SERVER_HOST: 0.0.0.0
      SERVER_BASEPATH: /apigatewayui/dashboardproxy
      NODE_OPTIONS: --max_old_space_size=1024
    mem_limit: 1gb
    links:
      - elasticsearch
    networks:
      - stack
    depends_on: 
      - elasticsearch

  # Shared Elasticsearch 
  elasticsearch:
    image: ${IMAGE_ELASTIC}:${TAG_ELASTIC}
    hostname: elasticsearch
    expose:
      - "9200"
      - "9300"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - http.port=9200
      - transport.port=9300
    volumes:
      - esdata:/data
    mem_limit: 3gb
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
      - stack
